name: CI

on:
  pull_request:
    branches: ["dev", "main"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run test -- --watchAll=false --ci --json --coverage --testLocationInResults --outputFile=report.json
      - name: Coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          output: report-markdown
          skip-step: all
      - name: Publish coverage results as a PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          message: ${{ steps.coverage.outputs.report }}
      - run: npm run build --if-present
